### ISSUE TITLE
Issue with defaultdict(list) saving to property.

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/atomlite#55]
Regardless of how, adding a `defaultdict(list)` instead of `dict()` leads to `TypeError: first argument must be callable or None`

MWE (from README):
```python
import atomlite
import rdkit.Chem as rdkit
from collections import defaultdict


# Create a database.
db = atomlite.Database("molecules.db")


# Create database entries.
d1 = defaultdict(list)
d2 = {}
d1['hello'] = [1,2,3]
d2['hello'] = [1,2,4]
entry1 = atomlite.Entry.from_rdkit("first", rdkit.MolFromSmiles("C"), d1)
entry2 = atomlite.Entry.from_rdkit("second", rdkit.MolFromSmiles("CN"), d2)
# Add entries to database.
db.add_entries([entry1, entry2])
# Retrieve entries from database.
for entry in db.get_entries(["first", "second"]):
  molecule = atomlite.json_to_rdkit(entry.molecule)
  print(entry.properties)

```

Traceback:
```
Traceback (most recent call last):
  File "/home/atarzia/workingspace/gists_testing/atomlite_test.py", line 18, in <module>
    db.add_entries([entry1, entry2])
  File "/home/atarzia/miniforge3/envs/lp/lib/python3.11/site-packages/atomlite/_internal/database.py", line 134, in add_entries
    self.connection.executemany(
  File "/home/atarzia/miniforge3/envs/lp/lib/python3.11/site-packages/atomlite/_internal/database.py", line 58, in _entry_to_sqlite
    d = asdict(entry)
        ^^^^^^^^^^^^^
  File "/home/atarzia/miniforge3/envs/lp/lib/python3.11/dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atarzia/miniforge3/envs/lp/lib/python3.11/dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atarzia/miniforge3/envs/lp/lib/python3.11/dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: first argument must be callable or None
```

**Comment by lukasturcani** [comment]
Interesting -- I've reproduced the error using Python 3.11 but it goes away with 3.12. I do want this to work on 3.11 so I will try a fix.

As a workaround, you can always do `dict(d1)` to convert your `defaultdict` into a plain `dict`
